 -- SUMA: a+b
 -- DIVISION: a/b a'div'b
 -- RESTO: a 'mod'b
 -- MULTIPLICACIÓN: a*b
 -- COMBINADOS: a - (b*c)
 -- OPERADORES LÓGICOS:
    -- a && b
    -- a || b
    -- a == b
    -- a /= b
    -- a > b
    -- a >= b